<!DOCTYPE html> 
<html lang="es">
<head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name='description' content='' />
	<meta name='author' content='' />
	<meta name='keywords' content='' />

	<title><?php echo title();?></title>
</head>
<body>
	<div id='main-content'>
		<div id='message-handler'></div>
		<?php echo $content; ?>
	</div>
	<div id="overlay"></div>
	<div id="fb-root"></div>
<script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js'></script>

<?php js_print(); ?>
</body>
</html>